const MyProjects = [
    {
        name:"Augio",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_1.jpg')
    },
    {
        name:"Roco",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_2.jpg')
    },
    {
        name:"Neo",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_3.jpg')
    },
    {
        name:"Zoma",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_4.png')
    },
    {
        name:"Liyu",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_5.png')
    },
    {
        name:"Tota",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_6.png')
    },
    {
        name:"Xerty",
        githubLink:"",
        link:"",
        figmaLink:"",
        image:require('../common/assets/images/project_img_7.png')
    },
]
export default MyProjects